backend = "glx";
vsync = true;

active-opacity = 1.0;
inactive-opacity = 0.85;
inactive-opacity-override = true;

focus-exclude = [
  "class_g = 'i3bar'",
  "class_g = 'polybar'",
  "class_g = 'dunst'"
];
